#!/bin/sh -e

export DESTDIR="$1"
export CFLAGS="$CFLAGS -I/src/oasis/out/pkg/libpng/include"
export LDFLAGS="$LDFLAGS -L/src/oasis/out/pkg/libpng"

meson setup \
    -Dprefix=/usr \
    -Ddefault_library=both \
    -Dbzip2=disabled \
    -Dzlib=disabled \
    output

samu -C output
samu -C output install
